<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Testimonials_Controller extends My_Template_Controller {

	// Disable this controller when Kohana is set to production mode.
	// See http://docs.kohanaphp.com/installation/deployment for more details.
	const ALLOW_PRODUCTION = FALSE;

	// Set the name of the template to use
	public $template = 'kohana/template';

	public $description = '';
	public $title = '';
	public $keywords = '';

	public function __construct() {
		parent::__construct();
		
		//set texts
		$method = $this->methodNameForSite('setTexts');
		$this->$method();
	}
	
	protected function setTexts_MCC()
	{
		$this->description = 'A new generation of custom chocolate favors is here with our state-of-the-art My Chocolate Coins customizers. We help you design your own personalized and custom chocolate coins for any occasion from party to wedding, bridal and baby shower, corporate and many more. Call us toll free at 1-866-230-7730.';
		$this->title = 'Testimonials - MyChocolateCoins.com';
		$this->keywords = 'chocolate hearts, custom chocolate hearts, personalized chocolate hearts, chocolate favors, custom chocolate favors, party favors, personalized chocolate favors, chocolate casino chips, chocolate poker chips, custom chocolate casino chips, casino party favors, wedding favors, personalized wedding favors, baby shower favors, bridal shower favors, chocolate gelt, chocolate gold hearts, chocolate party favors, chocolate candy favors, custom chocolate, custom chocolate poker chips, corporate favors';
	}
	
	protected function setTexts_MCH()
	{
		$this->description = 'A new generation of custom chocolate favors is here with our state-of-the-art My Chocolate Hearts customizers. We help you design your own personalized and custom chocolate hearts for any occasion from party to wedding, bridal and baby shower, corporate and many more. Call us toll free at 1-866-230-7730.';
		$this->title = 'Testimonials';
		$this->keywords = 'chocolate hearts, custom chocolate hearts, personalized chocolate hearts, chocolate favors, custom chocolate favors, party favors, personalized chocolate favors, chocolate casino chips, chocolate poker chips, custom chocolate casino chips, casino party favors, wedding favors, personalized wedding favors, baby shower favors, bridal shower favors, chocolate gelt, chocolate gold hearts, chocolate party favors, chocolate candy favors, custom chocolate, custom chocolate poker chips, corporate favors';
	}

	public function index()
	{
		// In Kohana, all views are loaded and treated as objects.
		$this->template->content = new View('testimonials');

		$this->template->metaDescription = $this->description;
		$this->template->metaKeywords = $this->keywords;	
		$this->template->metaTitle = $this->title;

		// You can assign anything variable to a view by using standard OOP
		// methods. In my welcome view, the $title variable will be assigned
		// the value I give it here.
		$this->template->title = $this->title;

		$db=new Database;
		$resultall = $db->query('SELECT t.* '.
								'FROM testimonials t '.
								'INNER JOIN sites_testimonials st ON t.id = st.testimonial_id '.
								'WHERE st.site_id = '.self::getCurrentSite()->id.' ORDER BY t.id DESC');
		$this->template->content->testimonialresults = $resultall;
		
		// getProducts is a method defined in Product_Model
		$products = new Product_Model;
		$this->template->content->productresults = $products->getProductsForSite(TRUE);  

		// getOccasions and getOccasion($id) is a method defined in Occasion_Model
		$occasions = new Occasion_Model;
		$this->template->content->occasionresults = $occasions->getOccasions(); 

		$this->template->content->message = "";
	}


	
	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller